#HEROKU_POSTGRESQL_CHARCOAL_URL
import os

#SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:lol@localhost:5432/findThemWeb'
SQLALCHEMY_DATABASE_URI = os.environ['HEROKU_POSTGRESQL_CHARCOAL_URL']
BOOTSTRAP_USE_MINIFIED = True
BOOTSTRAP_USE_CDN = True
BOOTSTRAP_FONTAWESOME = True
SECRET_KEY = 'devkey'
RECAPTCHA_PUBLIC_KEY = '6Lfol9cSAAAAADAkodaYl9wvQCwBMr3qGR_PPHcw'